/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as ApiVerifyTokenRouteImport } from './routes/api/verify-token'
import { Route as ApiExtensionTokenRouteImport } from './routes/api/extension-token'
import { Route as AuthSignupRouteRouteImport } from './routes/auth/signup/route'
import { Route as AuthSigninRouteRouteImport } from './routes/auth/signin/route'
import { Route as AuthenticatedPlaylistsRouteRouteImport } from './routes/_authenticated/playlists/route'
import { Route as AuthenticatedExtensionTokensRouteRouteImport } from './routes/_authenticated/extension-tokens/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedPlaylistsNameRouteRouteImport } from './routes/_authenticated/playlists/$name/route'
import { Route as AuthenticatedPlaylistsIndexRouteRouteImport } from './routes/_authenticated/playlists/index/route'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTokenRoute = ApiVerifyTokenRouteImport.update({
  id: '/api/verify-token',
  path: '/api/verify-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionTokenRoute = ApiExtensionTokenRouteImport.update({
  id: '/api/extension-token',
  path: '/api/extension-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRouteRoute = AuthSigninRouteRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaylistsRouteRoute =
  AuthenticatedPlaylistsRouteRouteImport.update({
    id: '/playlists',
    path: '/playlists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionTokensRouteRoute =
  AuthenticatedExtensionTokensRouteRouteImport.update({
    id: '/extension-tokens',
    path: '/extension-tokens',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaylistsNameRouteRoute =
  AuthenticatedPlaylistsNameRouteRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedPlaylistsRouteRoute,
  } as any)
const AuthenticatedPlaylistsIndexRouteRoute =
  AuthenticatedPlaylistsIndexRouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlaylistsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/extension-tokens': typeof AuthenticatedExtensionTokensRouteRoute
  '/playlists': typeof AuthenticatedPlaylistsRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/playlists/': typeof AuthenticatedPlaylistsIndexRouteRoute
  '/playlists/$name': typeof AuthenticatedPlaylistsNameRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/extension-tokens': typeof AuthenticatedExtensionTokensRouteRoute
  '/auth/signin': typeof AuthSigninRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/playlists': typeof AuthenticatedPlaylistsIndexRouteRoute
  '/playlists/$name': typeof AuthenticatedPlaylistsNameRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/extension-tokens': typeof AuthenticatedExtensionTokensRouteRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/_authenticated/playlists/': typeof AuthenticatedPlaylistsIndexRouteRoute
  '/_authenticated/playlists/$name': typeof AuthenticatedPlaylistsNameRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/extension-tokens'
    | '/playlists'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/playlists/'
    | '/playlists/$name'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/extension-tokens'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/playlists'
    | '/playlists/$name'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/extension-tokens'
    | '/_authenticated/playlists'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/_authenticated/playlists/'
    | '/_authenticated/playlists/$name'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSigninRouteRoute: typeof AuthSigninRouteRoute
  AuthSignupRouteRoute: typeof AuthSignupRouteRoute
  ApiExtensionTokenRoute: typeof ApiExtensionTokenRoute
  ApiVerifyTokenRoute: typeof ApiVerifyTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-token': {
      id: '/api/verify-token'
      path: '/api/verify-token'
      fullPath: '/api/verify-token'
      preLoaderRoute: typeof ApiVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension-token': {
      id: '/api/extension-token'
      path: '/api/extension-token'
      fullPath: '/api/extension-token'
      preLoaderRoute: typeof ApiExtensionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extension-tokens': {
      id: '/_authenticated/extension-tokens'
      path: '/extension-tokens'
      fullPath: '/extension-tokens'
      preLoaderRoute: typeof AuthenticatedExtensionTokensRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playlists/$name': {
      id: '/_authenticated/playlists/$name'
      path: '/$name'
      fullPath: '/playlists/$name'
      preLoaderRoute: typeof AuthenticatedPlaylistsNameRouteRouteImport
      parentRoute: typeof AuthenticatedPlaylistsRouteRoute
    }
    '/_authenticated/playlists/': {
      id: '/_authenticated/playlists/'
      path: '/'
      fullPath: '/playlists/'
      preLoaderRoute: typeof AuthenticatedPlaylistsIndexRouteRouteImport
      parentRoute: typeof AuthenticatedPlaylistsRouteRoute
    }
  }
}

interface AuthenticatedPlaylistsRouteRouteChildren {
  AuthenticatedPlaylistsIndexRouteRoute: typeof AuthenticatedPlaylistsIndexRouteRoute
  AuthenticatedPlaylistsNameRouteRoute: typeof AuthenticatedPlaylistsNameRouteRoute
}

const AuthenticatedPlaylistsRouteRouteChildren: AuthenticatedPlaylistsRouteRouteChildren =
  {
    AuthenticatedPlaylistsIndexRouteRoute:
      AuthenticatedPlaylistsIndexRouteRoute,
    AuthenticatedPlaylistsNameRouteRoute: AuthenticatedPlaylistsNameRouteRoute,
  }

const AuthenticatedPlaylistsRouteRouteWithChildren =
  AuthenticatedPlaylistsRouteRoute._addFileChildren(
    AuthenticatedPlaylistsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedExtensionTokensRouteRoute: typeof AuthenticatedExtensionTokensRouteRoute
  AuthenticatedPlaylistsRouteRoute: typeof AuthenticatedPlaylistsRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedExtensionTokensRouteRoute:
    AuthenticatedExtensionTokensRouteRoute,
  AuthenticatedPlaylistsRouteRoute:
    AuthenticatedPlaylistsRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSigninRouteRoute: AuthSigninRouteRoute,
  AuthSignupRouteRoute: AuthSignupRouteRoute,
  ApiExtensionTokenRoute: ApiExtensionTokenRoute,
  ApiVerifyTokenRoute: ApiVerifyTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
