/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyTokenRouteImport } from './routes/api/verify-token'
import { Route as ApiExtensionTokenRouteImport } from './routes/api/extension-token'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as ApiVideosIndexRouteImport } from './routes/api/videos/index'
import { Route as ApiTokensIndexRouteImport } from './routes/api/tokens/index'
import { Route as ApiTagsIndexRouteImport } from './routes/api/tags/index'
import { Route as ApiPreferencesIndexRouteImport } from './routes/api/preferences/index'
import { Route as ApiPlaylistsIndexRouteImport } from './routes/api/playlists/index'
import { Route as ApiOidcProvidersIndexRouteImport } from './routes/api/oidc-providers/index'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads/$filename'
import { Route as ApiTokensSplatRouteImport } from './routes/api/tokens/$'
import { Route as ApiTagsUnassignRouteImport } from './routes/api/tags/unassign'
import { Route as ApiTagsAssignRouteImport } from './routes/api/tags/assign'
import { Route as ApiTagsIdRouteImport } from './routes/api/tags/$id'
import { Route as ApiProcessVideoRouteImport } from './routes/api/process/video'
import { Route as ApiProcessPlaylistRouteImport } from './routes/api/process/playlist'
import { Route as ApiPlaylistsSplatRouteImport } from './routes/api/playlists/$'
import { Route as ApiOidcProvidersAllRouteImport } from './routes/api/oidc-providers/all'
import { Route as ApiOidcProvidersIdRouteImport } from './routes/api/oidc-providers/$id'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAppKnucklesRouteImport } from './routes/_authenticated/app/knuckles'
import { Route as AuthenticatedSettingsProfileRouteRouteImport } from './routes/_authenticated/settings/profile/route'
import { Route as AuthenticatedSettingsPreferencesRouteRouteImport } from './routes/_authenticated/settings/preferences/route'
import { Route as AuthenticatedSettingsPluginsRouteRouteImport } from './routes/_authenticated/settings/plugins/route'
import { Route as AuthenticatedSettingsOidcProvidersRouteRouteImport } from './routes/_authenticated/settings/oidc-providers/route'
import { Route as AuthenticatedAppPlaylistsRouteRouteImport } from './routes/_authenticated/app/playlists/route'
import { Route as ApiUserProfileIndexRouteImport } from './routes/api/user/profile/index'
import { Route as ApiConfigSmtpIndexRouteImport } from './routes/api/config/smtp/index'
import { Route as AuthenticatedSettingsProfileIndexRouteImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthenticatedSettingsPluginsIndexRouteImport } from './routes/_authenticated/settings/plugins/index'
import { Route as AuthenticatedSettingsOidcProvidersIndexRouteImport } from './routes/_authenticated/settings/oidc-providers/index'
import { Route as AuthenticatedSettingsEmailIndexRouteImport } from './routes/_authenticated/settings/email/index'
import { Route as AuthenticatedSettingsEmailVerificationIndexRouteImport } from './routes/_authenticated/settings/email-verification/index'
import { Route as AuthenticatedSettingsApiKeysIndexRouteImport } from './routes/_authenticated/settings/api-keys/index'
import { Route as AuthenticatedAppPlaylistsIndexRouteImport } from './routes/_authenticated/app/playlists/index'
import { Route as AuthenticatedAppDashboardIndexRouteImport } from './routes/_authenticated/app/dashboard/index'
import { Route as ApiConfigSmtpTestRouteImport } from './routes/api/config/smtp/test'
import { Route as ApiAuthOtpSplatRouteImport } from './routes/api/auth/otp/$'
import { Route as ApiAuthEmailOtpSplatRouteImport } from './routes/api/auth/email-otp/$'
import { Route as AuthenticatedSettingsAdminUsersRouteRouteImport } from './routes/_authenticated/settings/admin/users/route'
import { Route as AuthenticatedSettingsAdminOverviewRouteRouteImport } from './routes/_authenticated/settings/admin/overview/route'
import { Route as AuthenticatedAppPlaylistsNameRouteRouteImport } from './routes/_authenticated/app/playlists/$name/route'
import { Route as ApiPlaylistsIdVideosIndexRouteImport } from './routes/api/playlists/$id/videos/index'
import { Route as AuthenticatedSettingsPreferencesIndexRouteImport } from './routes/_authenticated/settings/preferences/index.'
import { Route as AuthenticatedSettingsAdminUsersIndexRouteImport } from './routes/_authenticated/settings/admin/users/index'
import { Route as AuthenticatedSettingsAdminOverviewIndexRouteImport } from './routes/_authenticated/settings/admin/overview/index'
import { Route as AuthenticatedAppPlaylistsNameIndexRouteImport } from './routes/_authenticated/app/playlists/$name/index'
import { Route as ApiPlaylistsIdVideosBulkRouteImport } from './routes/api/playlists/$id/videos/bulk'
import { Route as ApiPlaylistsIdVideosVideoIdRouteImport } from './routes/api/playlists/$id/videos/$videoId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTokenRoute = ApiVerifyTokenRouteImport.update({
  id: '/api/verify-token',
  path: '/api/verify-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionTokenRoute = ApiExtensionTokenRouteImport.update({
  id: '/api/extension-token',
  path: '/api/extension-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiVideosIndexRoute = ApiVideosIndexRouteImport.update({
  id: '/api/videos/',
  path: '/api/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensIndexRoute = ApiTokensIndexRouteImport.update({
  id: '/api/tokens/',
  path: '/api/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsIndexRoute = ApiTagsIndexRouteImport.update({
  id: '/api/tags/',
  path: '/api/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesIndexRoute = ApiPreferencesIndexRouteImport.update({
  id: '/api/preferences/',
  path: '/api/preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaylistsIndexRoute = ApiPlaylistsIndexRouteImport.update({
  id: '/api/playlists/',
  path: '/api/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcProvidersIndexRoute = ApiOidcProvidersIndexRouteImport.update({
  id: '/api/oidc-providers/',
  path: '/api/oidc-providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensSplatRoute = ApiTokensSplatRouteImport.update({
  id: '/api/tokens/$',
  path: '/api/tokens/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsUnassignRoute = ApiTagsUnassignRouteImport.update({
  id: '/api/tags/unassign',
  path: '/api/tags/unassign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsAssignRoute = ApiTagsAssignRouteImport.update({
  id: '/api/tags/assign',
  path: '/api/tags/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsIdRoute = ApiTagsIdRouteImport.update({
  id: '/api/tags/$id',
  path: '/api/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessVideoRoute = ApiProcessVideoRouteImport.update({
  id: '/api/process/video',
  path: '/api/process/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessPlaylistRoute = ApiProcessPlaylistRouteImport.update({
  id: '/api/process/playlist',
  path: '/api/process/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaylistsSplatRoute = ApiPlaylistsSplatRouteImport.update({
  id: '/api/playlists/$',
  path: '/api/playlists/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcProvidersAllRoute = ApiOidcProvidersAllRouteImport.update({
  id: '/api/oidc-providers/all',
  path: '/api/oidc-providers/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcProvidersIdRoute = ApiOidcProvidersIdRouteImport.update({
  id: '/api/oidc-providers/$id',
  path: '/api/oidc-providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppKnucklesRoute =
  AuthenticatedAppKnucklesRouteImport.update({
    id: '/knuckles',
    path: '/knuckles',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRouteRoute =
  AuthenticatedSettingsProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPreferencesRouteRoute =
  AuthenticatedSettingsPreferencesRouteRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPluginsRouteRoute =
  AuthenticatedSettingsPluginsRouteRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsOidcProvidersRouteRoute =
  AuthenticatedSettingsOidcProvidersRouteRouteImport.update({
    id: '/oidc-providers',
    path: '/oidc-providers',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsRouteRoute =
  AuthenticatedAppPlaylistsRouteRouteImport.update({
    id: '/playlists',
    path: '/playlists',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiUserProfileIndexRoute = ApiUserProfileIndexRouteImport.update({
  id: '/api/user/profile/',
  path: '/api/user/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigSmtpIndexRoute = ApiConfigSmtpIndexRouteImport.update({
  id: '/smtp/',
  path: '/smtp/',
  getParentRoute: () => ApiConfigRoute,
} as any)
const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsProfileRouteRoute,
  } as any)
const AuthenticatedSettingsPluginsIndexRoute =
  AuthenticatedSettingsPluginsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsPluginsRouteRoute,
  } as any)
const AuthenticatedSettingsOidcProvidersIndexRoute =
  AuthenticatedSettingsOidcProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsOidcProvidersRouteRoute,
  } as any)
const AuthenticatedSettingsEmailIndexRoute =
  AuthenticatedSettingsEmailIndexRouteImport.update({
    id: '/email/',
    path: '/email/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsEmailVerificationIndexRoute =
  AuthenticatedSettingsEmailVerificationIndexRouteImport.update({
    id: '/email-verification/',
    path: '/email-verification/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysIndexRoute =
  AuthenticatedSettingsApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsIndexRoute =
  AuthenticatedAppPlaylistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPlaylistsRouteRoute,
  } as any)
const AuthenticatedAppDashboardIndexRoute =
  AuthenticatedAppDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiConfigSmtpTestRoute = ApiConfigSmtpTestRouteImport.update({
  id: '/smtp/test',
  path: '/smtp/test',
  getParentRoute: () => ApiConfigRoute,
} as any)
const ApiAuthOtpSplatRoute = ApiAuthOtpSplatRouteImport.update({
  id: '/api/auth/otp/$',
  path: '/api/auth/otp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailOtpSplatRoute = ApiAuthEmailOtpSplatRouteImport.update({
  id: '/api/auth/email-otp/$',
  path: '/api/auth/email-otp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsAdminUsersRouteRoute =
  AuthenticatedSettingsAdminUsersRouteRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminOverviewRouteRoute =
  AuthenticatedSettingsAdminOverviewRouteRouteImport.update({
    id: '/admin/overview',
    path: '/admin/overview',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsNameRouteRoute =
  AuthenticatedAppPlaylistsNameRouteRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedAppPlaylistsRouteRoute,
  } as any)
const ApiPlaylistsIdVideosIndexRoute =
  ApiPlaylistsIdVideosIndexRouteImport.update({
    id: '/api/playlists/$id/videos/',
    path: '/api/playlists/$id/videos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsPreferencesIndexRoute =
  AuthenticatedSettingsPreferencesIndexRouteImport.update({
    id: '/index/',
    path: '/index/',
    getParentRoute: () => AuthenticatedSettingsPreferencesRouteRoute,
  } as any)
const AuthenticatedSettingsAdminUsersIndexRoute =
  AuthenticatedSettingsAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsAdminUsersRouteRoute,
  } as any)
const AuthenticatedSettingsAdminOverviewIndexRoute =
  AuthenticatedSettingsAdminOverviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsAdminOverviewRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsNameIndexRoute =
  AuthenticatedAppPlaylistsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPlaylistsNameRouteRoute,
  } as any)
const ApiPlaylistsIdVideosBulkRoute =
  ApiPlaylistsIdVideosBulkRouteImport.update({
    id: '/api/playlists/$id/videos/bulk',
    path: '/api/playlists/$id/videos/bulk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlaylistsIdVideosVideoIdRoute =
  ApiPlaylistsIdVideosVideoIdRouteImport.update({
    id: '/api/playlists/$id/videos/$videoId',
    path: '/api/playlists/$id/videos/$videoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/config': typeof ApiConfigRouteWithChildren
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/app/playlists': typeof AuthenticatedAppPlaylistsRouteRouteWithChildren
  '/settings/oidc-providers': typeof AuthenticatedSettingsOidcProvidersRouteRouteWithChildren
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRouteRouteWithChildren
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRouteRouteWithChildren
  '/settings/profile': typeof AuthenticatedSettingsProfileRouteRouteWithChildren
  '/app/knuckles': typeof AuthenticatedAppKnucklesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/oidc-providers/$id': typeof ApiOidcProvidersIdRoute
  '/api/oidc-providers/all': typeof ApiOidcProvidersAllRoute
  '/api/playlists/$': typeof ApiPlaylistsSplatRoute
  '/api/process/playlist': typeof ApiProcessPlaylistRoute
  '/api/process/video': typeof ApiProcessVideoRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/api/tags/assign': typeof ApiTagsAssignRoute
  '/api/tags/unassign': typeof ApiTagsUnassignRoute
  '/api/tokens/$': typeof ApiTokensSplatRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/oidc-providers': typeof ApiOidcProvidersIndexRoute
  '/api/playlists': typeof ApiPlaylistsIndexRoute
  '/api/preferences': typeof ApiPreferencesIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/api/tokens': typeof ApiTokensIndexRoute
  '/api/videos': typeof ApiVideosIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/app/playlists/$name': typeof AuthenticatedAppPlaylistsNameRouteRouteWithChildren
  '/settings/admin/overview': typeof AuthenticatedSettingsAdminOverviewRouteRouteWithChildren
  '/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRouteRouteWithChildren
  '/api/auth/email-otp/$': typeof ApiAuthEmailOtpSplatRoute
  '/api/auth/otp/$': typeof ApiAuthOtpSplatRoute
  '/api/config/smtp/test': typeof ApiConfigSmtpTestRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/app/playlists/': typeof AuthenticatedAppPlaylistsIndexRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysIndexRoute
  '/settings/email-verification': typeof AuthenticatedSettingsEmailVerificationIndexRoute
  '/settings/email': typeof AuthenticatedSettingsEmailIndexRoute
  '/settings/oidc-providers/': typeof AuthenticatedSettingsOidcProvidersIndexRoute
  '/settings/plugins/': typeof AuthenticatedSettingsPluginsIndexRoute
  '/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/api/config/smtp': typeof ApiConfigSmtpIndexRoute
  '/api/user/profile': typeof ApiUserProfileIndexRoute
  '/api/playlists/$id/videos/$videoId': typeof ApiPlaylistsIdVideosVideoIdRoute
  '/api/playlists/$id/videos/bulk': typeof ApiPlaylistsIdVideosBulkRoute
  '/app/playlists/$name/': typeof AuthenticatedAppPlaylistsNameIndexRoute
  '/settings/admin/overview/': typeof AuthenticatedSettingsAdminOverviewIndexRoute
  '/settings/admin/users/': typeof AuthenticatedSettingsAdminUsersIndexRoute
  '/settings/preferences/index': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/api/playlists/$id/videos': typeof ApiPlaylistsIdVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/config': typeof ApiConfigRouteWithChildren
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRouteRouteWithChildren
  '/app/knuckles': typeof AuthenticatedAppKnucklesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/oidc-providers/$id': typeof ApiOidcProvidersIdRoute
  '/api/oidc-providers/all': typeof ApiOidcProvidersAllRoute
  '/api/playlists/$': typeof ApiPlaylistsSplatRoute
  '/api/process/playlist': typeof ApiProcessPlaylistRoute
  '/api/process/video': typeof ApiProcessVideoRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/api/tags/assign': typeof ApiTagsAssignRoute
  '/api/tags/unassign': typeof ApiTagsUnassignRoute
  '/api/tokens/$': typeof ApiTokensSplatRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/oidc-providers': typeof ApiOidcProvidersIndexRoute
  '/api/playlists': typeof ApiPlaylistsIndexRoute
  '/api/preferences': typeof ApiPreferencesIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/api/tokens': typeof ApiTokensIndexRoute
  '/api/videos': typeof ApiVideosIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/api/auth/email-otp/$': typeof ApiAuthEmailOtpSplatRoute
  '/api/auth/otp/$': typeof ApiAuthOtpSplatRoute
  '/api/config/smtp/test': typeof ApiConfigSmtpTestRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/app/playlists': typeof AuthenticatedAppPlaylistsIndexRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysIndexRoute
  '/settings/email-verification': typeof AuthenticatedSettingsEmailVerificationIndexRoute
  '/settings/email': typeof AuthenticatedSettingsEmailIndexRoute
  '/settings/oidc-providers': typeof AuthenticatedSettingsOidcProvidersIndexRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/api/config/smtp': typeof ApiConfigSmtpIndexRoute
  '/api/user/profile': typeof ApiUserProfileIndexRoute
  '/api/playlists/$id/videos/$videoId': typeof ApiPlaylistsIdVideosVideoIdRoute
  '/api/playlists/$id/videos/bulk': typeof ApiPlaylistsIdVideosBulkRoute
  '/app/playlists/$name': typeof AuthenticatedAppPlaylistsNameIndexRoute
  '/settings/admin/overview': typeof AuthenticatedSettingsAdminOverviewIndexRoute
  '/settings/admin/users': typeof AuthenticatedSettingsAdminUsersIndexRoute
  '/settings/preferences/index': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/api/playlists/$id/videos': typeof ApiPlaylistsIdVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/config': typeof ApiConfigRouteWithChildren
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/_authenticated/app/playlists': typeof AuthenticatedAppPlaylistsRouteRouteWithChildren
  '/_authenticated/settings/oidc-providers': typeof AuthenticatedSettingsOidcProvidersRouteRouteWithChildren
  '/_authenticated/settings/plugins': typeof AuthenticatedSettingsPluginsRouteRouteWithChildren
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRouteRouteWithChildren
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRouteRouteWithChildren
  '/_authenticated/app/knuckles': typeof AuthenticatedAppKnucklesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/oidc-providers/$id': typeof ApiOidcProvidersIdRoute
  '/api/oidc-providers/all': typeof ApiOidcProvidersAllRoute
  '/api/playlists/$': typeof ApiPlaylistsSplatRoute
  '/api/process/playlist': typeof ApiProcessPlaylistRoute
  '/api/process/video': typeof ApiProcessVideoRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/api/tags/assign': typeof ApiTagsAssignRoute
  '/api/tags/unassign': typeof ApiTagsUnassignRoute
  '/api/tokens/$': typeof ApiTokensSplatRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/oidc-providers/': typeof ApiOidcProvidersIndexRoute
  '/api/playlists/': typeof ApiPlaylistsIndexRoute
  '/api/preferences/': typeof ApiPreferencesIndexRoute
  '/api/tags/': typeof ApiTagsIndexRoute
  '/api/tokens/': typeof ApiTokensIndexRoute
  '/api/videos/': typeof ApiVideosIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/_authenticated/app/playlists/$name': typeof AuthenticatedAppPlaylistsNameRouteRouteWithChildren
  '/_authenticated/settings/admin/overview': typeof AuthenticatedSettingsAdminOverviewRouteRouteWithChildren
  '/_authenticated/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRouteRouteWithChildren
  '/api/auth/email-otp/$': typeof ApiAuthEmailOtpSplatRoute
  '/api/auth/otp/$': typeof ApiAuthOtpSplatRoute
  '/api/config/smtp/test': typeof ApiConfigSmtpTestRoute
  '/_authenticated/app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/_authenticated/app/playlists/': typeof AuthenticatedAppPlaylistsIndexRoute
  '/_authenticated/settings/api-keys/': typeof AuthenticatedSettingsApiKeysIndexRoute
  '/_authenticated/settings/email-verification/': typeof AuthenticatedSettingsEmailVerificationIndexRoute
  '/_authenticated/settings/email/': typeof AuthenticatedSettingsEmailIndexRoute
  '/_authenticated/settings/oidc-providers/': typeof AuthenticatedSettingsOidcProvidersIndexRoute
  '/_authenticated/settings/plugins/': typeof AuthenticatedSettingsPluginsIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/api/config/smtp/': typeof ApiConfigSmtpIndexRoute
  '/api/user/profile/': typeof ApiUserProfileIndexRoute
  '/api/playlists/$id/videos/$videoId': typeof ApiPlaylistsIdVideosVideoIdRoute
  '/api/playlists/$id/videos/bulk': typeof ApiPlaylistsIdVideosBulkRoute
  '/_authenticated/app/playlists/$name/': typeof AuthenticatedAppPlaylistsNameIndexRoute
  '/_authenticated/settings/admin/overview/': typeof AuthenticatedSettingsAdminOverviewIndexRoute
  '/_authenticated/settings/admin/users/': typeof AuthenticatedSettingsAdminUsersIndexRoute
  '/_authenticated/settings/preferences/index/': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/api/playlists/$id/videos/': typeof ApiPlaylistsIdVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/settings'
    | '/api/config'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/app/playlists'
    | '/settings/oidc-providers'
    | '/settings/plugins'
    | '/settings/preferences'
    | '/settings/profile'
    | '/app/knuckles'
    | '/api/auth/$'
    | '/api/auth/me'
    | '/api/oidc-providers/$id'
    | '/api/oidc-providers/all'
    | '/api/playlists/$'
    | '/api/process/playlist'
    | '/api/process/video'
    | '/api/tags/$id'
    | '/api/tags/assign'
    | '/api/tags/unassign'
    | '/api/tokens/$'
    | '/api/uploads/$filename'
    | '/api/oidc-providers'
    | '/api/playlists'
    | '/api/preferences'
    | '/api/tags'
    | '/api/tokens'
    | '/api/videos'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/app/playlists/$name'
    | '/settings/admin/overview'
    | '/settings/admin/users'
    | '/api/auth/email-otp/$'
    | '/api/auth/otp/$'
    | '/api/config/smtp/test'
    | '/app/dashboard'
    | '/app/playlists/'
    | '/settings/api-keys'
    | '/settings/email-verification'
    | '/settings/email'
    | '/settings/oidc-providers/'
    | '/settings/plugins/'
    | '/settings/profile/'
    | '/api/config/smtp'
    | '/api/user/profile'
    | '/api/playlists/$id/videos/$videoId'
    | '/api/playlists/$id/videos/bulk'
    | '/app/playlists/$name/'
    | '/settings/admin/overview/'
    | '/settings/admin/users/'
    | '/settings/preferences/index'
    | '/api/playlists/$id/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/settings'
    | '/api/config'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/settings/preferences'
    | '/app/knuckles'
    | '/api/auth/$'
    | '/api/auth/me'
    | '/api/oidc-providers/$id'
    | '/api/oidc-providers/all'
    | '/api/playlists/$'
    | '/api/process/playlist'
    | '/api/process/video'
    | '/api/tags/$id'
    | '/api/tags/assign'
    | '/api/tags/unassign'
    | '/api/tokens/$'
    | '/api/uploads/$filename'
    | '/api/oidc-providers'
    | '/api/playlists'
    | '/api/preferences'
    | '/api/tags'
    | '/api/tokens'
    | '/api/videos'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/api/auth/email-otp/$'
    | '/api/auth/otp/$'
    | '/api/config/smtp/test'
    | '/app/dashboard'
    | '/app/playlists'
    | '/settings/api-keys'
    | '/settings/email-verification'
    | '/settings/email'
    | '/settings/oidc-providers'
    | '/settings/plugins'
    | '/settings/profile'
    | '/api/config/smtp'
    | '/api/user/profile'
    | '/api/playlists/$id/videos/$videoId'
    | '/api/playlists/$id/videos/bulk'
    | '/app/playlists/$name'
    | '/settings/admin/overview'
    | '/settings/admin/users'
    | '/settings/preferences/index'
    | '/api/playlists/$id/videos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/settings'
    | '/api/config'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/_authenticated/app/playlists'
    | '/_authenticated/settings/oidc-providers'
    | '/_authenticated/settings/plugins'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/profile'
    | '/_authenticated/app/knuckles'
    | '/api/auth/$'
    | '/api/auth/me'
    | '/api/oidc-providers/$id'
    | '/api/oidc-providers/all'
    | '/api/playlists/$'
    | '/api/process/playlist'
    | '/api/process/video'
    | '/api/tags/$id'
    | '/api/tags/assign'
    | '/api/tags/unassign'
    | '/api/tokens/$'
    | '/api/uploads/$filename'
    | '/api/oidc-providers/'
    | '/api/playlists/'
    | '/api/preferences/'
    | '/api/tags/'
    | '/api/tokens/'
    | '/api/videos/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-email/'
    | '/_authenticated/app/playlists/$name'
    | '/_authenticated/settings/admin/overview'
    | '/_authenticated/settings/admin/users'
    | '/api/auth/email-otp/$'
    | '/api/auth/otp/$'
    | '/api/config/smtp/test'
    | '/_authenticated/app/dashboard/'
    | '/_authenticated/app/playlists/'
    | '/_authenticated/settings/api-keys/'
    | '/_authenticated/settings/email-verification/'
    | '/_authenticated/settings/email/'
    | '/_authenticated/settings/oidc-providers/'
    | '/_authenticated/settings/plugins/'
    | '/_authenticated/settings/profile/'
    | '/api/config/smtp/'
    | '/api/user/profile/'
    | '/api/playlists/$id/videos/$videoId'
    | '/api/playlists/$id/videos/bulk'
    | '/_authenticated/app/playlists/$name/'
    | '/_authenticated/settings/admin/overview/'
    | '/_authenticated/settings/admin/users/'
    | '/_authenticated/settings/preferences/index/'
    | '/api/playlists/$id/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiConfigRoute: typeof ApiConfigRouteWithChildren
  ApiExtensionTokenRoute: typeof ApiExtensionTokenRoute
  ApiVerifyTokenRoute: typeof ApiVerifyTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiOidcProvidersIdRoute: typeof ApiOidcProvidersIdRoute
  ApiOidcProvidersAllRoute: typeof ApiOidcProvidersAllRoute
  ApiPlaylistsSplatRoute: typeof ApiPlaylistsSplatRoute
  ApiProcessPlaylistRoute: typeof ApiProcessPlaylistRoute
  ApiProcessVideoRoute: typeof ApiProcessVideoRoute
  ApiTagsIdRoute: typeof ApiTagsIdRoute
  ApiTagsAssignRoute: typeof ApiTagsAssignRoute
  ApiTagsUnassignRoute: typeof ApiTagsUnassignRoute
  ApiTokensSplatRoute: typeof ApiTokensSplatRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
  ApiOidcProvidersIndexRoute: typeof ApiOidcProvidersIndexRoute
  ApiPlaylistsIndexRoute: typeof ApiPlaylistsIndexRoute
  ApiPreferencesIndexRoute: typeof ApiPreferencesIndexRoute
  ApiTagsIndexRoute: typeof ApiTagsIndexRoute
  ApiTokensIndexRoute: typeof ApiTokensIndexRoute
  ApiVideosIndexRoute: typeof ApiVideosIndexRoute
  ApiAuthEmailOtpSplatRoute: typeof ApiAuthEmailOtpSplatRoute
  ApiAuthOtpSplatRoute: typeof ApiAuthOtpSplatRoute
  ApiUserProfileIndexRoute: typeof ApiUserProfileIndexRoute
  ApiPlaylistsIdVideosVideoIdRoute: typeof ApiPlaylistsIdVideosVideoIdRoute
  ApiPlaylistsIdVideosBulkRoute: typeof ApiPlaylistsIdVideosBulkRoute
  ApiPlaylistsIdVideosIndexRoute: typeof ApiPlaylistsIdVideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-token': {
      id: '/api/verify-token'
      path: '/api/verify-token'
      fullPath: '/api/verify-token'
      preLoaderRoute: typeof ApiVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension-token': {
      id: '/api/extension-token'
      path: '/api/extension-token'
      fullPath: '/api/extension-token'
      preLoaderRoute: typeof ApiExtensionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/videos/': {
      id: '/api/videos/'
      path: '/api/videos'
      fullPath: '/api/videos'
      preLoaderRoute: typeof ApiVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/': {
      id: '/api/tokens/'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/': {
      id: '/api/tags/'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences/': {
      id: '/api/preferences/'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists/': {
      id: '/api/playlists/'
      path: '/api/playlists'
      fullPath: '/api/playlists'
      preLoaderRoute: typeof ApiPlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc-providers/': {
      id: '/api/oidc-providers/'
      path: '/api/oidc-providers'
      fullPath: '/api/oidc-providers'
      preLoaderRoute: typeof ApiOidcProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/$': {
      id: '/api/tokens/$'
      path: '/api/tokens/$'
      fullPath: '/api/tokens/$'
      preLoaderRoute: typeof ApiTokensSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/unassign': {
      id: '/api/tags/unassign'
      path: '/api/tags/unassign'
      fullPath: '/api/tags/unassign'
      preLoaderRoute: typeof ApiTagsUnassignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/assign': {
      id: '/api/tags/assign'
      path: '/api/tags/assign'
      fullPath: '/api/tags/assign'
      preLoaderRoute: typeof ApiTagsAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/$id': {
      id: '/api/tags/$id'
      path: '/api/tags/$id'
      fullPath: '/api/tags/$id'
      preLoaderRoute: typeof ApiTagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process/video': {
      id: '/api/process/video'
      path: '/api/process/video'
      fullPath: '/api/process/video'
      preLoaderRoute: typeof ApiProcessVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process/playlist': {
      id: '/api/process/playlist'
      path: '/api/process/playlist'
      fullPath: '/api/process/playlist'
      preLoaderRoute: typeof ApiProcessPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists/$': {
      id: '/api/playlists/$'
      path: '/api/playlists/$'
      fullPath: '/api/playlists/$'
      preLoaderRoute: typeof ApiPlaylistsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc-providers/all': {
      id: '/api/oidc-providers/all'
      path: '/api/oidc-providers/all'
      fullPath: '/api/oidc-providers/all'
      preLoaderRoute: typeof ApiOidcProvidersAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc-providers/$id': {
      id: '/api/oidc-providers/$id'
      path: '/api/oidc-providers/$id'
      fullPath: '/api/oidc-providers/$id'
      preLoaderRoute: typeof ApiOidcProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/knuckles': {
      id: '/_authenticated/app/knuckles'
      path: '/knuckles'
      fullPath: '/app/knuckles'
      preLoaderRoute: typeof AuthenticatedAppKnucklesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/plugins': {
      id: '/_authenticated/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AuthenticatedSettingsPluginsRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/oidc-providers': {
      id: '/_authenticated/settings/oidc-providers'
      path: '/oidc-providers'
      fullPath: '/settings/oidc-providers'
      preLoaderRoute: typeof AuthenticatedSettingsOidcProvidersRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/app/playlists': {
      id: '/_authenticated/app/playlists'
      path: '/playlists'
      fullPath: '/app/playlists'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsRouteRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/user/profile/': {
      id: '/api/user/profile/'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/smtp/': {
      id: '/api/config/smtp/'
      path: '/smtp'
      fullPath: '/api/config/smtp'
      preLoaderRoute: typeof ApiConfigSmtpIndexRouteImport
      parentRoute: typeof ApiConfigRoute
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsProfileRouteRoute
    }
    '/_authenticated/settings/plugins/': {
      id: '/_authenticated/settings/plugins/'
      path: '/'
      fullPath: '/settings/plugins/'
      preLoaderRoute: typeof AuthenticatedSettingsPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsPluginsRouteRoute
    }
    '/_authenticated/settings/oidc-providers/': {
      id: '/_authenticated/settings/oidc-providers/'
      path: '/'
      fullPath: '/settings/oidc-providers/'
      preLoaderRoute: typeof AuthenticatedSettingsOidcProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsOidcProvidersRouteRoute
    }
    '/_authenticated/settings/email/': {
      id: '/_authenticated/settings/email/'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/email-verification/': {
      id: '/_authenticated/settings/email-verification/'
      path: '/email-verification'
      fullPath: '/settings/email-verification'
      preLoaderRoute: typeof AuthenticatedSettingsEmailVerificationIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys/': {
      id: '/_authenticated/settings/api-keys/'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/app/playlists/': {
      id: '/_authenticated/app/playlists/'
      path: '/'
      fullPath: '/app/playlists/'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsIndexRouteImport
      parentRoute: typeof AuthenticatedAppPlaylistsRouteRoute
    }
    '/_authenticated/app/dashboard/': {
      id: '/_authenticated/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/config/smtp/test': {
      id: '/api/config/smtp/test'
      path: '/smtp/test'
      fullPath: '/api/config/smtp/test'
      preLoaderRoute: typeof ApiConfigSmtpTestRouteImport
      parentRoute: typeof ApiConfigRoute
    }
    '/api/auth/otp/$': {
      id: '/api/auth/otp/$'
      path: '/api/auth/otp/$'
      fullPath: '/api/auth/otp/$'
      preLoaderRoute: typeof ApiAuthOtpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email-otp/$': {
      id: '/api/auth/email-otp/$'
      path: '/api/auth/email-otp/$'
      fullPath: '/api/auth/email-otp/$'
      preLoaderRoute: typeof ApiAuthEmailOtpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/admin/users': {
      id: '/_authenticated/settings/admin/users'
      path: '/admin/users'
      fullPath: '/settings/admin/users'
      preLoaderRoute: typeof AuthenticatedSettingsAdminUsersRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/admin/overview': {
      id: '/_authenticated/settings/admin/overview'
      path: '/admin/overview'
      fullPath: '/settings/admin/overview'
      preLoaderRoute: typeof AuthenticatedSettingsAdminOverviewRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/app/playlists/$name': {
      id: '/_authenticated/app/playlists/$name'
      path: '/$name'
      fullPath: '/app/playlists/$name'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsNameRouteRouteImport
      parentRoute: typeof AuthenticatedAppPlaylistsRouteRoute
    }
    '/api/playlists/$id/videos/': {
      id: '/api/playlists/$id/videos/'
      path: '/api/playlists/$id/videos'
      fullPath: '/api/playlists/$id/videos'
      preLoaderRoute: typeof ApiPlaylistsIdVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/preferences/index/': {
      id: '/_authenticated/settings/preferences/index/'
      path: '/index'
      fullPath: '/settings/preferences/index'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsPreferencesRouteRoute
    }
    '/_authenticated/settings/admin/users/': {
      id: '/_authenticated/settings/admin/users/'
      path: '/'
      fullPath: '/settings/admin/users/'
      preLoaderRoute: typeof AuthenticatedSettingsAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsAdminUsersRouteRoute
    }
    '/_authenticated/settings/admin/overview/': {
      id: '/_authenticated/settings/admin/overview/'
      path: '/'
      fullPath: '/settings/admin/overview/'
      preLoaderRoute: typeof AuthenticatedSettingsAdminOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsAdminOverviewRouteRoute
    }
    '/_authenticated/app/playlists/$name/': {
      id: '/_authenticated/app/playlists/$name/'
      path: '/'
      fullPath: '/app/playlists/$name/'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsNameIndexRouteImport
      parentRoute: typeof AuthenticatedAppPlaylistsNameRouteRoute
    }
    '/api/playlists/$id/videos/bulk': {
      id: '/api/playlists/$id/videos/bulk'
      path: '/api/playlists/$id/videos/bulk'
      fullPath: '/api/playlists/$id/videos/bulk'
      preLoaderRoute: typeof ApiPlaylistsIdVideosBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists/$id/videos/$videoId': {
      id: '/api/playlists/$id/videos/$videoId'
      path: '/api/playlists/$id/videos/$videoId'
      fullPath: '/api/playlists/$id/videos/$videoId'
      preLoaderRoute: typeof ApiPlaylistsIdVideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppPlaylistsNameRouteRouteChildren {
  AuthenticatedAppPlaylistsNameIndexRoute: typeof AuthenticatedAppPlaylistsNameIndexRoute
}

const AuthenticatedAppPlaylistsNameRouteRouteChildren: AuthenticatedAppPlaylistsNameRouteRouteChildren =
  {
    AuthenticatedAppPlaylistsNameIndexRoute:
      AuthenticatedAppPlaylistsNameIndexRoute,
  }

const AuthenticatedAppPlaylistsNameRouteRouteWithChildren =
  AuthenticatedAppPlaylistsNameRouteRoute._addFileChildren(
    AuthenticatedAppPlaylistsNameRouteRouteChildren,
  )

interface AuthenticatedAppPlaylistsRouteRouteChildren {
  AuthenticatedAppPlaylistsNameRouteRoute: typeof AuthenticatedAppPlaylistsNameRouteRouteWithChildren
  AuthenticatedAppPlaylistsIndexRoute: typeof AuthenticatedAppPlaylistsIndexRoute
}

const AuthenticatedAppPlaylistsRouteRouteChildren: AuthenticatedAppPlaylistsRouteRouteChildren =
  {
    AuthenticatedAppPlaylistsNameRouteRoute:
      AuthenticatedAppPlaylistsNameRouteRouteWithChildren,
    AuthenticatedAppPlaylistsIndexRoute: AuthenticatedAppPlaylistsIndexRoute,
  }

const AuthenticatedAppPlaylistsRouteRouteWithChildren =
  AuthenticatedAppPlaylistsRouteRoute._addFileChildren(
    AuthenticatedAppPlaylistsRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppPlaylistsRouteRoute: typeof AuthenticatedAppPlaylistsRouteRouteWithChildren
  AuthenticatedAppKnucklesRoute: typeof AuthenticatedAppKnucklesRoute
  AuthenticatedAppDashboardIndexRoute: typeof AuthenticatedAppDashboardIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppPlaylistsRouteRoute:
    AuthenticatedAppPlaylistsRouteRouteWithChildren,
  AuthenticatedAppKnucklesRoute: AuthenticatedAppKnucklesRoute,
  AuthenticatedAppDashboardIndexRoute: AuthenticatedAppDashboardIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedSettingsOidcProvidersRouteRouteChildren {
  AuthenticatedSettingsOidcProvidersIndexRoute: typeof AuthenticatedSettingsOidcProvidersIndexRoute
}

const AuthenticatedSettingsOidcProvidersRouteRouteChildren: AuthenticatedSettingsOidcProvidersRouteRouteChildren =
  {
    AuthenticatedSettingsOidcProvidersIndexRoute:
      AuthenticatedSettingsOidcProvidersIndexRoute,
  }

const AuthenticatedSettingsOidcProvidersRouteRouteWithChildren =
  AuthenticatedSettingsOidcProvidersRouteRoute._addFileChildren(
    AuthenticatedSettingsOidcProvidersRouteRouteChildren,
  )

interface AuthenticatedSettingsPluginsRouteRouteChildren {
  AuthenticatedSettingsPluginsIndexRoute: typeof AuthenticatedSettingsPluginsIndexRoute
}

const AuthenticatedSettingsPluginsRouteRouteChildren: AuthenticatedSettingsPluginsRouteRouteChildren =
  {
    AuthenticatedSettingsPluginsIndexRoute:
      AuthenticatedSettingsPluginsIndexRoute,
  }

const AuthenticatedSettingsPluginsRouteRouteWithChildren =
  AuthenticatedSettingsPluginsRouteRoute._addFileChildren(
    AuthenticatedSettingsPluginsRouteRouteChildren,
  )

interface AuthenticatedSettingsPreferencesRouteRouteChildren {
  AuthenticatedSettingsPreferencesIndexRoute: typeof AuthenticatedSettingsPreferencesIndexRoute
}

const AuthenticatedSettingsPreferencesRouteRouteChildren: AuthenticatedSettingsPreferencesRouteRouteChildren =
  {
    AuthenticatedSettingsPreferencesIndexRoute:
      AuthenticatedSettingsPreferencesIndexRoute,
  }

const AuthenticatedSettingsPreferencesRouteRouteWithChildren =
  AuthenticatedSettingsPreferencesRouteRoute._addFileChildren(
    AuthenticatedSettingsPreferencesRouteRouteChildren,
  )

interface AuthenticatedSettingsProfileRouteRouteChildren {
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
}

const AuthenticatedSettingsProfileRouteRouteChildren: AuthenticatedSettingsProfileRouteRouteChildren =
  {
    AuthenticatedSettingsProfileIndexRoute:
      AuthenticatedSettingsProfileIndexRoute,
  }

const AuthenticatedSettingsProfileRouteRouteWithChildren =
  AuthenticatedSettingsProfileRouteRoute._addFileChildren(
    AuthenticatedSettingsProfileRouteRouteChildren,
  )

interface AuthenticatedSettingsAdminOverviewRouteRouteChildren {
  AuthenticatedSettingsAdminOverviewIndexRoute: typeof AuthenticatedSettingsAdminOverviewIndexRoute
}

const AuthenticatedSettingsAdminOverviewRouteRouteChildren: AuthenticatedSettingsAdminOverviewRouteRouteChildren =
  {
    AuthenticatedSettingsAdminOverviewIndexRoute:
      AuthenticatedSettingsAdminOverviewIndexRoute,
  }

const AuthenticatedSettingsAdminOverviewRouteRouteWithChildren =
  AuthenticatedSettingsAdminOverviewRouteRoute._addFileChildren(
    AuthenticatedSettingsAdminOverviewRouteRouteChildren,
  )

interface AuthenticatedSettingsAdminUsersRouteRouteChildren {
  AuthenticatedSettingsAdminUsersIndexRoute: typeof AuthenticatedSettingsAdminUsersIndexRoute
}

const AuthenticatedSettingsAdminUsersRouteRouteChildren: AuthenticatedSettingsAdminUsersRouteRouteChildren =
  {
    AuthenticatedSettingsAdminUsersIndexRoute:
      AuthenticatedSettingsAdminUsersIndexRoute,
  }

const AuthenticatedSettingsAdminUsersRouteRouteWithChildren =
  AuthenticatedSettingsAdminUsersRouteRoute._addFileChildren(
    AuthenticatedSettingsAdminUsersRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsOidcProvidersRouteRoute: typeof AuthenticatedSettingsOidcProvidersRouteRouteWithChildren
  AuthenticatedSettingsPluginsRouteRoute: typeof AuthenticatedSettingsPluginsRouteRouteWithChildren
  AuthenticatedSettingsPreferencesRouteRoute: typeof AuthenticatedSettingsPreferencesRouteRouteWithChildren
  AuthenticatedSettingsProfileRouteRoute: typeof AuthenticatedSettingsProfileRouteRouteWithChildren
  AuthenticatedSettingsAdminOverviewRouteRoute: typeof AuthenticatedSettingsAdminOverviewRouteRouteWithChildren
  AuthenticatedSettingsAdminUsersRouteRoute: typeof AuthenticatedSettingsAdminUsersRouteRouteWithChildren
  AuthenticatedSettingsApiKeysIndexRoute: typeof AuthenticatedSettingsApiKeysIndexRoute
  AuthenticatedSettingsEmailVerificationIndexRoute: typeof AuthenticatedSettingsEmailVerificationIndexRoute
  AuthenticatedSettingsEmailIndexRoute: typeof AuthenticatedSettingsEmailIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsOidcProvidersRouteRoute:
      AuthenticatedSettingsOidcProvidersRouteRouteWithChildren,
    AuthenticatedSettingsPluginsRouteRoute:
      AuthenticatedSettingsPluginsRouteRouteWithChildren,
    AuthenticatedSettingsPreferencesRouteRoute:
      AuthenticatedSettingsPreferencesRouteRouteWithChildren,
    AuthenticatedSettingsProfileRouteRoute:
      AuthenticatedSettingsProfileRouteRouteWithChildren,
    AuthenticatedSettingsAdminOverviewRouteRoute:
      AuthenticatedSettingsAdminOverviewRouteRouteWithChildren,
    AuthenticatedSettingsAdminUsersRouteRoute:
      AuthenticatedSettingsAdminUsersRouteRouteWithChildren,
    AuthenticatedSettingsApiKeysIndexRoute:
      AuthenticatedSettingsApiKeysIndexRoute,
    AuthenticatedSettingsEmailVerificationIndexRoute:
      AuthenticatedSettingsEmailVerificationIndexRoute,
    AuthenticatedSettingsEmailIndexRoute: AuthenticatedSettingsEmailIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiConfigRouteChildren {
  ApiConfigSmtpTestRoute: typeof ApiConfigSmtpTestRoute
  ApiConfigSmtpIndexRoute: typeof ApiConfigSmtpIndexRoute
}

const ApiConfigRouteChildren: ApiConfigRouteChildren = {
  ApiConfigSmtpTestRoute: ApiConfigSmtpTestRoute,
  ApiConfigSmtpIndexRoute: ApiConfigSmtpIndexRoute,
}

const ApiConfigRouteWithChildren = ApiConfigRoute._addFileChildren(
  ApiConfigRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiConfigRoute: ApiConfigRouteWithChildren,
  ApiExtensionTokenRoute: ApiExtensionTokenRoute,
  ApiVerifyTokenRoute: ApiVerifyTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiOidcProvidersIdRoute: ApiOidcProvidersIdRoute,
  ApiOidcProvidersAllRoute: ApiOidcProvidersAllRoute,
  ApiPlaylistsSplatRoute: ApiPlaylistsSplatRoute,
  ApiProcessPlaylistRoute: ApiProcessPlaylistRoute,
  ApiProcessVideoRoute: ApiProcessVideoRoute,
  ApiTagsIdRoute: ApiTagsIdRoute,
  ApiTagsAssignRoute: ApiTagsAssignRoute,
  ApiTagsUnassignRoute: ApiTagsUnassignRoute,
  ApiTokensSplatRoute: ApiTokensSplatRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
  ApiOidcProvidersIndexRoute: ApiOidcProvidersIndexRoute,
  ApiPlaylistsIndexRoute: ApiPlaylistsIndexRoute,
  ApiPreferencesIndexRoute: ApiPreferencesIndexRoute,
  ApiTagsIndexRoute: ApiTagsIndexRoute,
  ApiTokensIndexRoute: ApiTokensIndexRoute,
  ApiVideosIndexRoute: ApiVideosIndexRoute,
  ApiAuthEmailOtpSplatRoute: ApiAuthEmailOtpSplatRoute,
  ApiAuthOtpSplatRoute: ApiAuthOtpSplatRoute,
  ApiUserProfileIndexRoute: ApiUserProfileIndexRoute,
  ApiPlaylistsIdVideosVideoIdRoute: ApiPlaylistsIdVideosVideoIdRoute,
  ApiPlaylistsIdVideosBulkRoute: ApiPlaylistsIdVideosBulkRoute,
  ApiPlaylistsIdVideosIndexRoute: ApiPlaylistsIdVideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
