/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyTokenRouteImport } from './routes/api/verify-token'
import { Route as ApiExtensionTokenRouteImport } from './routes/api/extension-token'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as ApiVideosIndexRouteImport } from './routes/api/videos/index'
import { Route as ApiTokensIndexRouteImport } from './routes/api/tokens/index'
import { Route as ApiPlaylistsIndexRouteImport } from './routes/api/playlists/index'
import { Route as ApiTokensSplatRouteImport } from './routes/api/tokens/$'
import { Route as ApiPlaylistsSplatRouteImport } from './routes/api/playlists/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAppKnucklesRouteImport } from './routes/_authenticated/app/knuckles'
import { Route as AuthenticatedSettingsProfileRouteRouteImport } from './routes/_authenticated/settings/profile/route'
import { Route as AuthenticatedSettingsPreferencesRouteRouteImport } from './routes/_authenticated/settings/preferences/route'
import { Route as AuthenticatedSettingsPluginsRouteRouteImport } from './routes/_authenticated/settings/plugins/route'
import { Route as AuthenticatedAppPlaylistsRouteRouteImport } from './routes/_authenticated/app/playlists/route'
import { Route as AuthenticatedSettingsApiKeysIndexRouteImport } from './routes/_authenticated/settings/api-keys/index'
import { Route as AuthenticatedAppPlaylistsIndexRouteImport } from './routes/_authenticated/app/playlists/index'
import { Route as AuthenticatedAppDashboardIndexRouteImport } from './routes/_authenticated/app/dashboard/index'
import { Route as AuthenticatedAppPlaylistsNameRouteRouteImport } from './routes/_authenticated/app/playlists/$name/route'
import { Route as AuthenticatedAppPlaylistsNameIndexRouteImport } from './routes/_authenticated/app/playlists/$name/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTokenRoute = ApiVerifyTokenRouteImport.update({
  id: '/api/verify-token',
  path: '/api/verify-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionTokenRoute = ApiExtensionTokenRouteImport.update({
  id: '/api/extension-token',
  path: '/api/extension-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIndexRoute = ApiVideosIndexRouteImport.update({
  id: '/api/videos/',
  path: '/api/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensIndexRoute = ApiTokensIndexRouteImport.update({
  id: '/api/tokens/',
  path: '/api/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaylistsIndexRoute = ApiPlaylistsIndexRouteImport.update({
  id: '/api/playlists/',
  path: '/api/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensSplatRoute = ApiTokensSplatRouteImport.update({
  id: '/api/tokens/$',
  path: '/api/tokens/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaylistsSplatRoute = ApiPlaylistsSplatRouteImport.update({
  id: '/api/playlists/$',
  path: '/api/playlists/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppKnucklesRoute =
  AuthenticatedAppKnucklesRouteImport.update({
    id: '/knuckles',
    path: '/knuckles',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRouteRoute =
  AuthenticatedSettingsProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPreferencesRouteRoute =
  AuthenticatedSettingsPreferencesRouteRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPluginsRouteRoute =
  AuthenticatedSettingsPluginsRouteRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsRouteRoute =
  AuthenticatedAppPlaylistsRouteRouteImport.update({
    id: '/playlists',
    path: '/playlists',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysIndexRoute =
  AuthenticatedSettingsApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsIndexRoute =
  AuthenticatedAppPlaylistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPlaylistsRouteRoute,
  } as any)
const AuthenticatedAppDashboardIndexRoute =
  AuthenticatedAppDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsNameRouteRoute =
  AuthenticatedAppPlaylistsNameRouteRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedAppPlaylistsRouteRoute,
  } as any)
const AuthenticatedAppPlaylistsNameIndexRoute =
  AuthenticatedAppPlaylistsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPlaylistsNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/app/playlists': typeof AuthenticatedAppPlaylistsRouteRouteWithChildren
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRouteRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRouteRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRouteRoute
  '/app/knuckles': typeof AuthenticatedAppKnucklesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playlists/$': typeof ApiPlaylistsSplatRoute
  '/api/tokens/$': typeof ApiTokensSplatRoute
  '/api/playlists': typeof ApiPlaylistsIndexRoute
  '/api/tokens': typeof ApiTokensIndexRoute
  '/api/videos': typeof ApiVideosIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/app/playlists/$name': typeof AuthenticatedAppPlaylistsNameRouteRouteWithChildren
  '/app/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/app/playlists/': typeof AuthenticatedAppPlaylistsIndexRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysIndexRoute
  '/app/playlists/$name/': typeof AuthenticatedAppPlaylistsNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRouteRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRouteRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRouteRoute
  '/app/knuckles': typeof AuthenticatedAppKnucklesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playlists/$': typeof ApiPlaylistsSplatRoute
  '/api/tokens/$': typeof ApiTokensSplatRoute
  '/api/playlists': typeof ApiPlaylistsIndexRoute
  '/api/tokens': typeof ApiTokensIndexRoute
  '/api/videos': typeof ApiVideosIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/app/playlists': typeof AuthenticatedAppPlaylistsIndexRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysIndexRoute
  '/app/playlists/$name': typeof AuthenticatedAppPlaylistsNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/api/extension-token': typeof ApiExtensionTokenRoute
  '/api/verify-token': typeof ApiVerifyTokenRoute
  '/_authenticated/app/playlists': typeof AuthenticatedAppPlaylistsRouteRouteWithChildren
  '/_authenticated/settings/plugins': typeof AuthenticatedSettingsPluginsRouteRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRouteRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRouteRoute
  '/_authenticated/app/knuckles': typeof AuthenticatedAppKnucklesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playlists/$': typeof ApiPlaylistsSplatRoute
  '/api/tokens/$': typeof ApiTokensSplatRoute
  '/api/playlists/': typeof ApiPlaylistsIndexRoute
  '/api/tokens/': typeof ApiTokensIndexRoute
  '/api/videos/': typeof ApiVideosIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/_authenticated/app/playlists/$name': typeof AuthenticatedAppPlaylistsNameRouteRouteWithChildren
  '/_authenticated/app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/_authenticated/app/playlists/': typeof AuthenticatedAppPlaylistsIndexRoute
  '/_authenticated/settings/api-keys/': typeof AuthenticatedSettingsApiKeysIndexRoute
  '/_authenticated/app/playlists/$name/': typeof AuthenticatedAppPlaylistsNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/settings'
    | '/api/config'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/app/playlists'
    | '/settings/plugins'
    | '/settings/preferences'
    | '/settings/profile'
    | '/app/knuckles'
    | '/api/auth/$'
    | '/api/playlists/$'
    | '/api/tokens/$'
    | '/api/playlists'
    | '/api/tokens'
    | '/api/videos'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/playlists/$name'
    | '/app/dashboard'
    | '/app/playlists/'
    | '/settings/api-keys'
    | '/app/playlists/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/settings'
    | '/api/config'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/settings/plugins'
    | '/settings/preferences'
    | '/settings/profile'
    | '/app/knuckles'
    | '/api/auth/$'
    | '/api/playlists/$'
    | '/api/tokens/$'
    | '/api/playlists'
    | '/api/tokens'
    | '/api/videos'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/dashboard'
    | '/app/playlists'
    | '/settings/api-keys'
    | '/app/playlists/$name'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/app'
    | '/_authenticated/settings'
    | '/api/config'
    | '/api/extension-token'
    | '/api/verify-token'
    | '/_authenticated/app/playlists'
    | '/_authenticated/settings/plugins'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/profile'
    | '/_authenticated/app/knuckles'
    | '/api/auth/$'
    | '/api/playlists/$'
    | '/api/tokens/$'
    | '/api/playlists/'
    | '/api/tokens/'
    | '/api/videos/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/_authenticated/app/playlists/$name'
    | '/_authenticated/app/dashboard/'
    | '/_authenticated/app/playlists/'
    | '/_authenticated/settings/api-keys/'
    | '/_authenticated/app/playlists/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiConfigRoute: typeof ApiConfigRoute
  ApiExtensionTokenRoute: typeof ApiExtensionTokenRoute
  ApiVerifyTokenRoute: typeof ApiVerifyTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPlaylistsSplatRoute: typeof ApiPlaylistsSplatRoute
  ApiTokensSplatRoute: typeof ApiTokensSplatRoute
  ApiPlaylistsIndexRoute: typeof ApiPlaylistsIndexRoute
  ApiTokensIndexRoute: typeof ApiTokensIndexRoute
  ApiVideosIndexRoute: typeof ApiVideosIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-token': {
      id: '/api/verify-token'
      path: '/api/verify-token'
      fullPath: '/api/verify-token'
      preLoaderRoute: typeof ApiVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension-token': {
      id: '/api/extension-token'
      path: '/api/extension-token'
      fullPath: '/api/extension-token'
      preLoaderRoute: typeof ApiExtensionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/': {
      id: '/api/videos/'
      path: '/api/videos'
      fullPath: '/api/videos'
      preLoaderRoute: typeof ApiVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/': {
      id: '/api/tokens/'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists/': {
      id: '/api/playlists/'
      path: '/api/playlists'
      fullPath: '/api/playlists'
      preLoaderRoute: typeof ApiPlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/$': {
      id: '/api/tokens/$'
      path: '/api/tokens/$'
      fullPath: '/api/tokens/$'
      preLoaderRoute: typeof ApiTokensSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists/$': {
      id: '/api/playlists/$'
      path: '/api/playlists/$'
      fullPath: '/api/playlists/$'
      preLoaderRoute: typeof ApiPlaylistsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/knuckles': {
      id: '/_authenticated/app/knuckles'
      path: '/knuckles'
      fullPath: '/app/knuckles'
      preLoaderRoute: typeof AuthenticatedAppKnucklesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/plugins': {
      id: '/_authenticated/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AuthenticatedSettingsPluginsRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/app/playlists': {
      id: '/_authenticated/app/playlists'
      path: '/playlists'
      fullPath: '/app/playlists'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsRouteRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/settings/api-keys/': {
      id: '/_authenticated/settings/api-keys/'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/app/playlists/': {
      id: '/_authenticated/app/playlists/'
      path: '/'
      fullPath: '/app/playlists/'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsIndexRouteImport
      parentRoute: typeof AuthenticatedAppPlaylistsRouteRoute
    }
    '/_authenticated/app/dashboard/': {
      id: '/_authenticated/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/playlists/$name': {
      id: '/_authenticated/app/playlists/$name'
      path: '/$name'
      fullPath: '/app/playlists/$name'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsNameRouteRouteImport
      parentRoute: typeof AuthenticatedAppPlaylistsRouteRoute
    }
    '/_authenticated/app/playlists/$name/': {
      id: '/_authenticated/app/playlists/$name/'
      path: '/'
      fullPath: '/app/playlists/$name/'
      preLoaderRoute: typeof AuthenticatedAppPlaylistsNameIndexRouteImport
      parentRoute: typeof AuthenticatedAppPlaylistsNameRouteRoute
    }
  }
}

interface AuthenticatedAppPlaylistsNameRouteRouteChildren {
  AuthenticatedAppPlaylistsNameIndexRoute: typeof AuthenticatedAppPlaylistsNameIndexRoute
}

const AuthenticatedAppPlaylistsNameRouteRouteChildren: AuthenticatedAppPlaylistsNameRouteRouteChildren =
  {
    AuthenticatedAppPlaylistsNameIndexRoute:
      AuthenticatedAppPlaylistsNameIndexRoute,
  }

const AuthenticatedAppPlaylistsNameRouteRouteWithChildren =
  AuthenticatedAppPlaylistsNameRouteRoute._addFileChildren(
    AuthenticatedAppPlaylistsNameRouteRouteChildren,
  )

interface AuthenticatedAppPlaylistsRouteRouteChildren {
  AuthenticatedAppPlaylistsNameRouteRoute: typeof AuthenticatedAppPlaylistsNameRouteRouteWithChildren
  AuthenticatedAppPlaylistsIndexRoute: typeof AuthenticatedAppPlaylistsIndexRoute
}

const AuthenticatedAppPlaylistsRouteRouteChildren: AuthenticatedAppPlaylistsRouteRouteChildren =
  {
    AuthenticatedAppPlaylistsNameRouteRoute:
      AuthenticatedAppPlaylistsNameRouteRouteWithChildren,
    AuthenticatedAppPlaylistsIndexRoute: AuthenticatedAppPlaylistsIndexRoute,
  }

const AuthenticatedAppPlaylistsRouteRouteWithChildren =
  AuthenticatedAppPlaylistsRouteRoute._addFileChildren(
    AuthenticatedAppPlaylistsRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppPlaylistsRouteRoute: typeof AuthenticatedAppPlaylistsRouteRouteWithChildren
  AuthenticatedAppKnucklesRoute: typeof AuthenticatedAppKnucklesRoute
  AuthenticatedAppDashboardIndexRoute: typeof AuthenticatedAppDashboardIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppPlaylistsRouteRoute:
    AuthenticatedAppPlaylistsRouteRouteWithChildren,
  AuthenticatedAppKnucklesRoute: AuthenticatedAppKnucklesRoute,
  AuthenticatedAppDashboardIndexRoute: AuthenticatedAppDashboardIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsPluginsRouteRoute: typeof AuthenticatedSettingsPluginsRouteRoute
  AuthenticatedSettingsPreferencesRouteRoute: typeof AuthenticatedSettingsPreferencesRouteRoute
  AuthenticatedSettingsProfileRouteRoute: typeof AuthenticatedSettingsProfileRouteRoute
  AuthenticatedSettingsApiKeysIndexRoute: typeof AuthenticatedSettingsApiKeysIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsPluginsRouteRoute:
      AuthenticatedSettingsPluginsRouteRoute,
    AuthenticatedSettingsPreferencesRouteRoute:
      AuthenticatedSettingsPreferencesRouteRoute,
    AuthenticatedSettingsProfileRouteRoute:
      AuthenticatedSettingsProfileRouteRoute,
    AuthenticatedSettingsApiKeysIndexRoute:
      AuthenticatedSettingsApiKeysIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiConfigRoute: ApiConfigRoute,
  ApiExtensionTokenRoute: ApiExtensionTokenRoute,
  ApiVerifyTokenRoute: ApiVerifyTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPlaylistsSplatRoute: ApiPlaylistsSplatRoute,
  ApiTokensSplatRoute: ApiTokensSplatRoute,
  ApiPlaylistsIndexRoute: ApiPlaylistsIndexRoute,
  ApiTokensIndexRoute: ApiTokensIndexRoute,
  ApiVideosIndexRoute: ApiVideosIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
