// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CleanExpiredSessions = `-- name: CleanExpiredSessions :exec
delete from sessions
where expires_at < now()
`

func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, CleanExpiredSessions)
	return err
}

const CreateSession = `-- name: CreateSession :one
insert into sessions (user_id, token, expires_at)
values ($1, $2, $3)
returning id, user_id, token, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg *CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, CreateSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const CreateUser = `-- name: CreateUser :one
insert into users (email, password_hash)
values ($1, $2)
returning id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteSession = `-- name: DeleteSession :exec
delete from sessions
where token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, DeleteSession, token)
	return err
}

const DeleteUserSessions = `-- name: DeleteUserSessions :exec
delete from sessions
where user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, DeleteUserSessions, userID)
	return err
}

const GetSessionByToken = `-- name: GetSessionByToken :one
select s.id, s.user_id, s.token, s.expires_at, s.created_at, u.id as user_id, u.email as user_email
from sessions s
join users u on s.user_id = u.id
where s.token = $1
  and s.expires_at > now()
limit 1
`

type GetSessionByTokenRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID_2  int64              `json:"user_id_2"`
	UserEmail string             `json:"user_email"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (*GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, GetSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID_2,
		&i.UserEmail,
	)
	return &i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, created_at, updated_at from users
where email = $1
limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
select id, email, password_hash, created_at, updated_at from users
where id = $1
limit 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
