// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package db

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT key, value, updated_at
FROM config
WHERE key = $1
`

func (q *Queries) GetConfig(ctx context.Context, key string) (*Config, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var i Config
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO config (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = now()
RETURNING key, value, updated_at
`

type UpsertConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg *UpsertConfigParams) (*Config, error) {
	row := q.db.QueryRow(ctx, upsertConfig, arg.Key, arg.Value)
	var i Config
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return &i, err
}

const listConfigs = `-- name: ListConfigs :many
SELECT key, value, updated_at
FROM config
ORDER BY key
`

func (q *Queries) ListConfigs(ctx context.Context) ([]*Config, error) {
	rows, err := q.db.Query(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

