// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           string             `json:"id"`
	AccountID    string             `json:"account_id"`
	ProviderID   string             `json:"provider_id"`
	UserID       string             `json:"user_id"`
	AccessToken  *string            `json:"access_token"`
	RefreshToken *string            `json:"refresh_token"`
	IDToken      *string            `json:"id_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Password     *string            `json:"password"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Config struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Video struct {
	ID            int64              `json:"id"`
	VideoID       string             `json:"video_id"`
	NormalizedUrl string             `json:"normalized_url"`
	OriginalUrl   string             `json:"original_url"`
	Title         string             `json:"title"`
	Channel       string             `json:"channel"`
	UserID        int64              `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
