// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOIDCProvider = `-- name: CreateOIDCProvider :one
INSERT INTO oidc_providers (provider_id, name, discovery_url, client_id, client_secret, scopes, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, name, discovery_url, client_id, client_secret, scopes, enabled, created_at, updated_at
`

type CreateOIDCProviderParams struct {
	ProviderID   string   `json:"provider_id"`
	Name         string   `json:"name"`
	DiscoveryUrl string   `json:"discovery_url"`
	ClientID     string   `json:"client_id"`
	ClientSecret string   `json:"client_secret"`
	Scopes       []string `json:"scopes"`
	Enabled      bool     `json:"enabled"`
}

func (q *Queries) CreateOIDCProvider(ctx context.Context, arg *CreateOIDCProviderParams) (*OidcProvider, error) {
	row := q.db.QueryRow(ctx, CreateOIDCProvider,
		arg.ProviderID,
		arg.Name,
		arg.DiscoveryUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.DiscoveryUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteOIDCProvider = `-- name: DeleteOIDCProvider :exec
DELETE FROM oidc_providers
WHERE id = $1
`

func (q *Queries) DeleteOIDCProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOIDCProvider, id)
	return err
}

const GetOIDCProvider = `-- name: GetOIDCProvider :one
SELECT id, provider_id, name, discovery_url, client_id, client_secret, scopes, enabled, created_at, updated_at
FROM oidc_providers
WHERE id = $1
`

func (q *Queries) GetOIDCProvider(ctx context.Context, id pgtype.UUID) (*OidcProvider, error) {
	row := q.db.QueryRow(ctx, GetOIDCProvider, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.DiscoveryUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetOIDCProviderByProviderID = `-- name: GetOIDCProviderByProviderID :one
SELECT id, provider_id, name, discovery_url, client_id, client_secret, scopes, enabled, created_at, updated_at
FROM oidc_providers
WHERE provider_id = $1
`

func (q *Queries) GetOIDCProviderByProviderID(ctx context.Context, providerID string) (*OidcProvider, error) {
	row := q.db.QueryRow(ctx, GetOIDCProviderByProviderID, providerID)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.DiscoveryUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const ListAllOIDCProviders = `-- name: ListAllOIDCProviders :many
SELECT id, provider_id, name, discovery_url, client_id, client_secret, scopes, enabled, created_at, updated_at
FROM oidc_providers
ORDER BY name
`

func (q *Queries) ListAllOIDCProviders(ctx context.Context) ([]*OidcProvider, error) {
	rows, err := q.db.Query(ctx, ListAllOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OidcProvider{}
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.DiscoveryUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEnabledOIDCProviders = `-- name: ListEnabledOIDCProviders :many
SELECT id, provider_id, name, discovery_url, client_id, client_secret, scopes, enabled, created_at, updated_at
FROM oidc_providers
WHERE enabled = true
ORDER BY name
`

func (q *Queries) ListEnabledOIDCProviders(ctx context.Context) ([]*OidcProvider, error) {
	rows, err := q.db.Query(ctx, ListEnabledOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OidcProvider{}
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.DiscoveryUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateOIDCProvider = `-- name: UpdateOIDCProvider :one
UPDATE oidc_providers
SET name = $2,
    discovery_url = $3,
    client_id = $4,
    client_secret = $5,
    scopes = $6,
    enabled = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, provider_id, name, discovery_url, client_id, client_secret, scopes, enabled, created_at, updated_at
`

type UpdateOIDCProviderParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	DiscoveryUrl string      `json:"discovery_url"`
	ClientID     string      `json:"client_id"`
	ClientSecret string      `json:"client_secret"`
	Scopes       []string    `json:"scopes"`
	Enabled      bool        `json:"enabled"`
}

func (q *Queries) UpdateOIDCProvider(ctx context.Context, arg *UpdateOIDCProviderParams) (*OidcProvider, error) {
	row := q.db.QueryRow(ctx, UpdateOIDCProvider,
		arg.ID,
		arg.Name,
		arg.DiscoveryUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.DiscoveryUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
