// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddVideoToPlaylist = `-- name: AddVideoToPlaylist :one
insert into playlist_videos (playlist_id, video_id, position)
values ($1, $2, $3)
on conflict (playlist_id, video_id) do nothing
returning playlist_id, video_id, position, created_at
`

type AddVideoToPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	VideoID    int64 `json:"video_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) AddVideoToPlaylist(ctx context.Context, arg *AddVideoToPlaylistParams) (*PlaylistVideo, error) {
	row := q.db.QueryRow(ctx, AddVideoToPlaylist, arg.PlaylistID, arg.VideoID, arg.Position)
	var i PlaylistVideo
	err := row.Scan(
		&i.PlaylistID,
		&i.VideoID,
		&i.Position,
		&i.CreatedAt,
	)
	return &i, err
}

const AddVideoToPlaylistByName = `-- name: AddVideoToPlaylistByName :exec
insert into playlist_videos (playlist_id, video_id, position)
select p.id, $2, $3
from playlists p
where p.user_id = $1 and p.name = $4
on conflict (playlist_id, video_id) do nothing
`

type AddVideoToPlaylistByNameParams struct {
	UserID   string `json:"user_id"`
	VideoID  int64  `json:"video_id"`
	Position int32  `json:"position"`
	Name     string `json:"name"`
}

func (q *Queries) AddVideoToPlaylistByName(ctx context.Context, arg *AddVideoToPlaylistByNameParams) error {
	_, err := q.db.Exec(ctx, AddVideoToPlaylistByName,
		arg.UserID,
		arg.VideoID,
		arg.Position,
		arg.Name,
	)
	return err
}

const CreatePlaylist = `-- name: CreatePlaylist :one
insert into playlists (user_id, name)
values ($1, $2)
returning id, user_id, name, created_at, updated_at
`

type CreatePlaylistParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg *CreatePlaylistParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, CreatePlaylist, arg.UserID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeletePlaylist = `-- name: DeletePlaylist :exec
delete from playlists
where user_id = $1 and name = $2
`

type DeletePlaylistParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg *DeletePlaylistParams) error {
	_, err := q.db.Exec(ctx, DeletePlaylist, arg.UserID, arg.Name)
	return err
}

const GetPlaylistByName = `-- name: GetPlaylistByName :one
select id, user_id, name, created_at, updated_at
from playlists
where user_id = $1 and name = $2
`

type GetPlaylistByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetPlaylistByName(ctx context.Context, arg *GetPlaylistByNameParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, GetPlaylistByName, arg.UserID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetPlaylistIDByName = `-- name: GetPlaylistIDByName :one
select id from playlists
where user_id = $1 and name = $2
`

type GetPlaylistIDByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetPlaylistIDByName(ctx context.Context, arg *GetPlaylistIDByNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, GetPlaylistIDByName, arg.UserID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetPlaylistVideoCount = `-- name: GetPlaylistVideoCount :one
select count(*) as count
from playlist_videos pv
join playlists p on pv.playlist_id = p.id
where p.user_id = $1 and p.name = $2
`

type GetPlaylistVideoCountParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetPlaylistVideoCount(ctx context.Context, arg *GetPlaylistVideoCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, GetPlaylistVideoCount, arg.UserID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetPlaylistVideos = `-- name: GetPlaylistVideos :many
select v.id, v.video_id, v.normalized_url, v.original_url, v.title, v.channel, v.user_id, v.created_at, pv.position, pv.created_at as added_at
from playlist_videos pv
join videos v on pv.video_id = v.id
join playlists p on pv.playlist_id = p.id
where p.user_id = $1 and p.name = $2
order by pv.position, pv.created_at
`

type GetPlaylistVideosParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type GetPlaylistVideosRow struct {
	ID            int64              `json:"id"`
	VideoID       string             `json:"video_id"`
	NormalizedUrl string             `json:"normalized_url"`
	OriginalUrl   string             `json:"original_url"`
	Title         string             `json:"title"`
	Channel       string             `json:"channel"`
	UserID        string             `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Position      int32              `json:"position"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
}

func (q *Queries) GetPlaylistVideos(ctx context.Context, arg *GetPlaylistVideosParams) ([]*GetPlaylistVideosRow, error) {
	rows, err := q.db.Query(ctx, GetPlaylistVideos, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPlaylistVideosRow{}
	for rows.Next() {
		var i GetPlaylistVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.NormalizedUrl,
			&i.OriginalUrl,
			&i.Title,
			&i.Channel,
			&i.UserID,
			&i.CreatedAt,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlaylistsByUser = `-- name: ListPlaylistsByUser :many
select id, user_id, name, created_at, updated_at
from playlists
where user_id = $1
order by created_at desc
`

func (q *Queries) ListPlaylistsByUser(ctx context.Context, userID string) ([]*Playlist, error) {
	rows, err := q.db.Query(ctx, ListPlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveVideoFromPlaylist = `-- name: RemoveVideoFromPlaylist :exec
delete from playlist_videos pv
using playlists p
where pv.playlist_id = p.id
  and p.user_id = $1
  and p.name = $2
  and pv.video_id = $3
`

type RemoveVideoFromPlaylistParams struct {
	UserID  string `json:"user_id"`
	Name    string `json:"name"`
	VideoID int64  `json:"video_id"`
}

func (q *Queries) RemoveVideoFromPlaylist(ctx context.Context, arg *RemoveVideoFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, RemoveVideoFromPlaylist, arg.UserID, arg.Name, arg.VideoID)
	return err
}

const UpdatePlaylistByName = `-- name: UpdatePlaylistByName :one
update playlists
set name = $3, updated_at = now()
where user_id = $1 and name = $2
returning id, user_id, name, created_at, updated_at
`

type UpdatePlaylistByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Name_2 string `json:"name_2"`
}

func (q *Queries) UpdatePlaylistByName(ctx context.Context, arg *UpdatePlaylistByNameParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, UpdatePlaylistByName, arg.UserID, arg.Name, arg.Name_2)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
