// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddVideoToPlaylist = `-- name: AddVideoToPlaylist :one
insert into playlist_videos (playlist_id, video_id, position)
values ($1, $2, $3)
on conflict (playlist_id, video_id) do nothing
returning playlist_id, video_id, position, created_at
`

type AddVideoToPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	VideoID    int64 `json:"video_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) AddVideoToPlaylist(ctx context.Context, arg *AddVideoToPlaylistParams) (*PlaylistVideo, error) {
	row := q.db.QueryRow(ctx, AddVideoToPlaylist, arg.PlaylistID, arg.VideoID, arg.Position)
	var i PlaylistVideo
	err := row.Scan(
		&i.PlaylistID,
		&i.VideoID,
		&i.Position,
		&i.CreatedAt,
	)
	return &i, err
}

const CreatePlaylist = `-- name: CreatePlaylist :one
insert into playlists (user_id, name)
values ($1, $2)
returning id, user_id, name, created_at, updated_at
`

type CreatePlaylistParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg *CreatePlaylistParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, CreatePlaylist, arg.UserID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeletePlaylist = `-- name: DeletePlaylist :exec
delete from playlists
where id = $1 and user_id = $2
`

type DeletePlaylistParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg *DeletePlaylistParams) error {
	_, err := q.db.Exec(ctx, DeletePlaylist, arg.ID, arg.UserID)
	return err
}

const GetPlaylistByID = `-- name: GetPlaylistByID :one
select id, user_id, name, created_at, updated_at
from playlists
where id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id int64) (*Playlist, error) {
	row := q.db.QueryRow(ctx, GetPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetPlaylistVideoCount = `-- name: GetPlaylistVideoCount :one
select count(*) as count
from playlist_videos
where playlist_id = $1
`

func (q *Queries) GetPlaylistVideoCount(ctx context.Context, playlistID int64) (int64, error) {
	row := q.db.QueryRow(ctx, GetPlaylistVideoCount, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetPlaylistVideos = `-- name: GetPlaylistVideos :many
select v.id, v.video_id, v.normalized_url, v.original_url, v.title, v.channel, v.user_id, v.created_at, pv.position, pv.created_at as added_at
from playlist_videos pv
join videos v on pv.video_id = v.id
where pv.playlist_id = $1
order by pv.position, pv.created_at
`

type GetPlaylistVideosRow struct {
	ID            int64              `json:"id"`
	VideoID       string             `json:"video_id"`
	NormalizedUrl string             `json:"normalized_url"`
	OriginalUrl   string             `json:"original_url"`
	Title         string             `json:"title"`
	Channel       string             `json:"channel"`
	UserID        string             `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Position      int32              `json:"position"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
}

func (q *Queries) GetPlaylistVideos(ctx context.Context, playlistID int64) ([]*GetPlaylistVideosRow, error) {
	rows, err := q.db.Query(ctx, GetPlaylistVideos, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPlaylistVideosRow{}
	for rows.Next() {
		var i GetPlaylistVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.NormalizedUrl,
			&i.OriginalUrl,
			&i.Title,
			&i.Channel,
			&i.UserID,
			&i.CreatedAt,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlaylistsByUser = `-- name: ListPlaylistsByUser :many
select id, user_id, name, created_at, updated_at
from playlists
where user_id = $1
order by created_at desc
`

func (q *Queries) ListPlaylistsByUser(ctx context.Context, userID string) ([]*Playlist, error) {
	rows, err := q.db.Query(ctx, ListPlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveVideoFromPlaylist = `-- name: RemoveVideoFromPlaylist :exec
delete from playlist_videos
where playlist_id = $1 and video_id = $2
`

type RemoveVideoFromPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	VideoID    int64 `json:"video_id"`
}

func (q *Queries) RemoveVideoFromPlaylist(ctx context.Context, arg *RemoveVideoFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, RemoveVideoFromPlaylist, arg.PlaylistID, arg.VideoID)
	return err
}

const UpdatePlaylist = `-- name: UpdatePlaylist :one
update playlists
set name = $2, updated_at = now()
where id = $1 and user_id = $3
returning id, user_id, name, created_at, updated_at
`

type UpdatePlaylistParams struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg *UpdatePlaylistParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, UpdatePlaylist, arg.ID, arg.Name, arg.UserID)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
