// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CleanExpiredSessions(ctx context.Context) error
	CreateSession(ctx context.Context, arg *CreateSessionParams) (*Session, error)
	CreateVideo(ctx context.Context, arg *CreateVideoParams) (*Video, error)
	DeleteSession(ctx context.Context, token string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetConfig(ctx context.Context, key string) (*Config, error)
	GetSessionByToken(ctx context.Context, token string) (*GetSessionByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
	GetUserByVerificationToken(ctx context.Context, value string) (*User, error)
	GetVerificationByValue(ctx context.Context, value string) (*Verification, error)
	GetVideoByURL(ctx context.Context, normalizedUrl string) (*Video, error)
	ListConfigs(ctx context.Context) ([]*Config, error)
	ListRecentVerifications(ctx context.Context) ([]*Verification, error)
	ListVideos(ctx context.Context, userID string) ([]*Video, error)
	UpsertConfig(ctx context.Context, arg *UpsertConfigParams) (*Config, error)
}

var _ Querier = (*Queries)(nil)
