// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetConfig(ctx context.Context, key string) (*Config, error)
	UpsertConfig(ctx context.Context, arg *UpsertConfigParams) (*Config, error)
	ListConfigs(ctx context.Context) ([]*Config, error)
}

var _ Querier = (*Queries)(nil)

