// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"
)

const GetUserPreferences = `-- name: GetUserPreferences :one
select user_id, primary_color, created_at, updated_at
from user_preferences
where user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (*UserPreference, error) {
	row := q.db.QueryRow(ctx, GetUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.PrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpsertUserPreferences = `-- name: UpsertUserPreferences :one
insert into user_preferences (user_id, primary_color)
values ($1, $2)
on conflict (user_id) do update
set primary_color = $2, updated_at = now()
returning user_id, primary_color, created_at, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID       string `json:"user_id"`
	PrimaryColor string `json:"primary_color"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg *UpsertUserPreferencesParams) (*UserPreference, error) {
	row := q.db.QueryRow(ctx, UpsertUserPreferences, arg.UserID, arg.PrimaryColor)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.PrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
