// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package db

import (
	"context"
)

const CreateVideo = `-- name: CreateVideo :one
INSERT INTO videos (video_id, normalized_url, original_url, title, channel, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (normalized_url) DO NOTHING
RETURNING id, video_id, normalized_url, original_url, title, channel, user_id, created_at
`

type CreateVideoParams struct {
	VideoID       string `json:"video_id"`
	NormalizedUrl string `json:"normalized_url"`
	OriginalUrl   string `json:"original_url"`
	Title         string `json:"title"`
	Channel       string `json:"channel"`
	UserID        string `json:"user_id"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg *CreateVideoParams) (*Video, error) {
	row := q.db.QueryRow(ctx, CreateVideo,
		arg.VideoID,
		arg.NormalizedUrl,
		arg.OriginalUrl,
		arg.Title,
		arg.Channel,
		arg.UserID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.NormalizedUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Channel,
		&i.UserID,
		&i.CreatedAt,
	)
	return &i, err
}

const GetVideoByID = `-- name: GetVideoByID :one
SELECT id, video_id, normalized_url, original_url, title, channel, user_id, created_at
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id int64) (*Video, error) {
	row := q.db.QueryRow(ctx, GetVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.NormalizedUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Channel,
		&i.UserID,
		&i.CreatedAt,
	)
	return &i, err
}

const GetVideoByURL = `-- name: GetVideoByURL :one
SELECT id, video_id, normalized_url, original_url, title, channel, user_id, created_at
FROM videos
WHERE normalized_url = $1
`

func (q *Queries) GetVideoByURL(ctx context.Context, normalizedUrl string) (*Video, error) {
	row := q.db.QueryRow(ctx, GetVideoByURL, normalizedUrl)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.NormalizedUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Channel,
		&i.UserID,
		&i.CreatedAt,
	)
	return &i, err
}

const ListVideos = `-- name: ListVideos :many
SELECT id, video_id, normalized_url, original_url, title, channel, user_id, created_at
FROM videos
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVideos(ctx context.Context, userID string) ([]*Video, error) {
	rows, err := q.db.Query(ctx, ListVideos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.NormalizedUrl,
			&i.OriginalUrl,
			&i.Title,
			&i.Channel,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListVideosFiltered = `-- name: ListVideosFiltered :many
SELECT id, video_id, normalized_url, original_url, title, channel, user_id, created_at
FROM videos
WHERE user_id = $1
  AND channel = ANY($2::text[])
ORDER BY created_at DESC
`

type ListVideosFilteredParams struct {
	UserID  string   `json:"user_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) ListVideosFiltered(ctx context.Context, arg *ListVideosFilteredParams) ([]*Video, error) {
	rows, err := q.db.Query(ctx, ListVideosFiltered, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.NormalizedUrl,
			&i.OriginalUrl,
			&i.Title,
			&i.Channel,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
